name: Build
on:
  push:
  pull_request:
  repository_dispatch:
    types: [build-pre-rel]
jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Check out source code
        uses: actions/checkout@v3
        with:
          # needed to calc build number via git log --oneline
          fetch-depth: 0

      - name: Build
        run: .\doit.bat -ci
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/rel64/SumatraPDF.exe
